import "./globals.css";
import "./styles/mission.css";
import "./styles/services.css";
import "./styles/key-projects.css";
import "./styles/portfolio-section.css";
import "./styles/eyes-on.css";
import "./styles/contact-form.css";
import "./styles/faqs.css";
import "./styles/footer.css";
import "./styles/services-page.css";
import "./styles/portfolio-page.css";
import Footer from "./components/Footer";
import MouseLight from "./components/MouseLight";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <MouseLight />
        {children}
        <Footer />
      </body>
    </html>
  );
}
